/**
 * High-fidelity fallback dataset mirroring seeded pharmaceutical records
 */

export const MOCK_COMPANY = {
  id: "comp-001",
  name: "Apex Pharma Distributors Ltd.",
  tradeLicenseNo: "TRAD-DH-2024-8849",
  drugLicenseNo: "DL-DH-09182-W",
  taxIdTin: "8291039182",
  email: "info@apexpharmadist.com",
  phone: "+880 1711 000111",
  address: "Plot 14, Commercial Zone, Tejgaon Industrial Area",
  city: "Dhaka",
  country: "Bangladesh",
  currency: "BDT",
  defaultCreditDays: 30,
  defaultVatPercent: 0.0,
  enableFefoStrict: true,
  lowStockThreshold: 20,
  nearExpiryDays: 90,
  invoiceFooterText: "Goods once sold are subject to wholesale returns policy within 7 days. Licensed wholesale drug stockist.",
};

export const MOCK_USERS = [
  { id: "usr-1", name: "Rafiqul Islam", email: "admin@pharmadist.com", role: "SUPER_ADMIN", phone: "+880 1819 112233", status: "ACTIVE" },
  { id: "usr-2", name: "Kamal Hossain", email: "sales.manager@pharmadist.com", role: "SALES_MANAGER", phone: "+880 1712 334455", status: "ACTIVE" },
  { id: "usr-3", name: "Tareq Mahmud", email: "warehouse@pharmadist.com", role: "WAREHOUSE_MANAGER", phone: "+880 1913 556677", status: "ACTIVE" },
  { id: "usr-4", name: "Shahidul Alam", email: "accounts@pharmadist.com", role: "ACCOUNTS_OFFICER", phone: "+880 1515 778899", status: "ACTIVE" },
  { id: "usr-5", name: "Tariqul Islam", email: "tariqul.mr@pharmadist.com", role: "SALESMAN", phone: "+880 1718 112233", status: "ACTIVE" },
];

export const MOCK_CATEGORIES = [
  { id: "cat-1", name: "Antibiotics & Anti-infectives", description: "Broad-spectrum and narrow-spectrum antibacterial formulations" },
  { id: "cat-2", name: "Analgesics & Antipyretics", description: "Pain management, NSAIDs, and fever reducing agents" },
  { id: "cat-3", name: "Cardiovascular & Antihypertensives", description: "Blood pressure regulation, statins, and cardiac medicines" },
  { id: "cat-4", name: "Gastrointestinal & Antacids", description: "Proton pump inhibitors, H2 blockers, and antacids" },
  { id: "cat-5", name: "Respiratory & Antiallergics", description: "Bronchodilators, antihistamines, and cough syrups" },
];

export const MOCK_EXPENSE_CATEGORIES = [
  { id: "exp-cat-1", name: "Logistics & Van Fuel" },
  { id: "exp-cat-2", name: "Cold Chain Electricity & Generator" },
  { id: "exp-cat-3", name: "Warehouse Packaging Materials" },
  { id: "exp-cat-4", name: "Office Rent & Admin" },
  { id: "exp-cat-5", name: "Sales Team TA/DA & Travel" },
];

export const MOCK_PURCHASES = [
  {
    id: "po-101",
    poNumber: "PO-2026-0044",
    supplierId: "sup-2",
    supplierName: "Beximco Pharmaceuticals Ltd.",
    purchaseDate: "2026-08-14",
    supplierInvoiceNo: "BX-INV-99201",
    totalAmount: 188000,
    paidAmount: 188000,
    dueAmount: 0,
    status: "RECEIVED" as const,
    itemsCount: 2,
  },
  {
    id: "po-102",
    poNumber: "PO-2026-0045",
    supplierId: "sup-1",
    supplierName: "Square Pharmaceuticals PLC",
    purchaseDate: "2026-08-18",
    supplierInvoiceNo: "SQ-INV-88192",
    totalAmount: 325000,
    paidAmount: 180000,
    dueAmount: 145000,
    status: "RECEIVED" as const,
    itemsCount: 4,
  },
  {
    id: "po-103",
    poNumber: "PO-2026-0046",
    supplierId: "sup-3",
    supplierName: "Incepta Pharmaceuticals Ltd.",
    purchaseDate: "2026-08-21",
    supplierInvoiceNo: "INC-PO-0192",
    totalAmount: 120000,
    paidAmount: 120000,
    dueAmount: 0,
    status: "ORDERED" as const,
    itemsCount: 1,
  },
];

export const MOCK_SUPPLIERS = [
  {
    id: "sup-1",
    name: "Square Pharmaceuticals PLC",
    contactPerson: "Dr. Asif Mahmud",
    email: "corporate@squarepharma.com",
    phone: "+880 1713 001122",
    address: "Square Centre, 48 Mohakhali C/A",
    city: "Dhaka",
    country: "Bangladesh",
    drugLicenseNo: "MFG-DL-00192",
    tradeLicenseNo: "TL-SQ-8812",
    taxIdTin: "9102839182",
    creditDays: 45,
    creditLimit: 5000000,
    currentPayable: 145000,
    status: "ACTIVE" as const,
    totalPurchases: 1250000,
  },
  {
    id: "sup-2",
    name: "Beximco Pharmaceuticals Ltd.",
    contactPerson: "Nazmul Hassan",
    email: "supply@beximcopharma.com",
    phone: "+880 1714 223344",
    address: "19 Dhanmondi R/A, Road 7",
    city: "Dhaka",
    country: "Bangladesh",
    drugLicenseNo: "MFG-DL-00284",
    tradeLicenseNo: "TL-BX-9941",
    taxIdTin: "1928374650",
    creditDays: 30,
    creditLimit: 4000000,
    currentPayable: 82000,
    status: "ACTIVE" as const,
    totalPurchases: 980000,
  },
  {
    id: "sup-3",
    name: "Incepta Pharmaceuticals Ltd.",
    contactPerson: "Kazi Alamgir",
    email: "orders@inceptapharma.com",
    phone: "+880 1819 445566",
    address: "40 Shahid Tajuddin Ahmed Sarani, Tejgaon",
    city: "Dhaka",
    country: "Bangladesh",
    drugLicenseNo: "MFG-DL-00351",
    tradeLicenseNo: "TL-INC-7731",
    taxIdTin: "3847291048",
    creditDays: 30,
    creditLimit: 3500000,
    currentPayable: 0,
    status: "ACTIVE" as const,
    totalPurchases: 720000,
  },
  {
    id: "sup-4",
    name: "Renata Limited",
    contactPerson: "Tanvir Ahmed",
    email: "commercial@renata-ltd.com",
    phone: "+880 1912 778899",
    address: "Plot 1, Milk Vita Road, Section 7, Mirpur",
    city: "Dhaka",
    country: "Bangladesh",
    drugLicenseNo: "MFG-DL-00412",
    tradeLicenseNo: "TL-RN-4421",
    taxIdTin: "7382910294",
    creditDays: 60,
    creditLimit: 3000000,
    currentPayable: 35000,
    status: "ACTIVE" as const,
    totalPurchases: 540000,
  },
];

export const MOCK_WAREHOUSES = [
  { id: "wh-1", name: "Central Hub Tejgaon", code: "WH-DH-01", isCentralHub: true, hasColdRoom: true, hasNarcoticsSafe: true, address: "Tejgaon I/A, Dhaka" },
  { id: "wh-2", name: "Chittagong Depot", code: "WH-CTG-02", isCentralHub: false, hasColdRoom: true, hasNarcoticsSafe: false, address: "Agrabad C/A, Chittagong" },
];

export const MOCK_RACKS = [
  { id: "rack-1", warehouseId: "wh-1", rackNumber: "A-01", sectionName: "Antibiotics Tier 1" },
  { id: "rack-2", warehouseId: "wh-1", rackNumber: "B-03", sectionName: "Analgesics & Pain" },
  { id: "rack-3", warehouseId: "wh-1", rackNumber: "CR-01", sectionName: "Cold Room 2-8C" },
];

export const MOCK_MEDICINES = [
  {
    id: "med-1",
    brandName: "Napa Extra",
    genericName: "Paracetamol + Caffeine",
    strength: "500mg + 65mg",
    dosageForm: "TABLET" as const,
    categoryId: "cat-2",
    categoryName: "Analgesics & Antipyretics",
    supplierId: "sup-2",
    supplierName: "Beximco Pharmaceuticals Ltd.",
    unitTradePrice: 2.20,
    unitMrp: 2.50,
    wholesaleBasePrice: 2.05,
    vatPercent: 0,
    storageCondition: "ROOM_TEMPERATURE" as const,
    reorderAlertLevel: 200,
    totalStockOnHand: 1500,
    isPrescriptionRequired: false,
    isColdChain: false,
    isNarcotic: false,
    primaryUnitName: "Box (20x10)",
    status: "ACTIVE" as const,
  },
  {
    id: "med-2",
    brandName: "Ace Plus",
    genericName: "Paracetamol + Caffeine",
    strength: "500mg + 65mg",
    dosageForm: "TABLET" as const,
    categoryId: "cat-2",
    categoryName: "Analgesics & Antipyretics",
    supplierId: "sup-1",
    supplierName: "Square Pharmaceuticals PLC",
    unitTradePrice: 2.18,
    unitMrp: 2.50,
    wholesaleBasePrice: 2.02,
    vatPercent: 0,
    storageCondition: "ROOM_TEMPERATURE" as const,
    reorderAlertLevel: 250,
    totalStockOnHand: 2200,
    isPrescriptionRequired: false,
    isColdChain: false,
    isNarcotic: false,
    primaryUnitName: "Box (20x10)",
    status: "ACTIVE" as const,
  },
  {
    id: "med-3",
    brandName: "Seclo 20",
    genericName: "Omeprazole",
    strength: "20mg",
    dosageForm: "CAPSULE" as const,
    categoryId: "cat-4",
    categoryName: "Gastrointestinal & Antacids",
    supplierId: "sup-1",
    supplierName: "Square Pharmaceuticals PLC",
    unitTradePrice: 4.40,
    unitMrp: 5.00,
    wholesaleBasePrice: 4.10,
    vatPercent: 0,
    storageCondition: "ROOM_TEMPERATURE" as const,
    reorderAlertLevel: 150,
    totalStockOnHand: 840,
    isPrescriptionRequired: true,
    isColdChain: false,
    isNarcotic: false,
    primaryUnitName: "Box (10x10)",
    status: "ACTIVE" as const,
  },
  {
    id: "med-4",
    brandName: "Ciprocin 500",
    genericName: "Ciprofloxacin",
    strength: "500mg",
    dosageForm: "TABLET" as const,
    categoryId: "cat-1",
    categoryName: "Antibiotics & Anti-infectives",
    supplierId: "sup-1",
    supplierName: "Square Pharmaceuticals PLC",
    unitTradePrice: 13.20,
    unitMrp: 15.00,
    wholesaleBasePrice: 12.30,
    vatPercent: 0,
    storageCondition: "ROOM_TEMPERATURE" as const,
    reorderAlertLevel: 100,
    totalStockOnHand: 450,
    isPrescriptionRequired: true,
    isColdChain: false,
    isNarcotic: false,
    primaryUnitName: "Box (5x10)",
    status: "ACTIVE" as const,
  },
  {
    id: "med-5",
    brandName: "Maxpro 20",
    genericName: "Esomeprazole",
    strength: "20mg",
    dosageForm: "CAPSULE" as const,
    categoryId: "cat-4",
    categoryName: "Gastrointestinal & Antacids",
    supplierId: "sup-4",
    supplierName: "Renata Limited",
    unitTradePrice: 6.16,
    unitMrp: 7.00,
    wholesaleBasePrice: 5.75,
    vatPercent: 0,
    storageCondition: "ROOM_TEMPERATURE" as const,
    reorderAlertLevel: 120,
    totalStockOnHand: 620,
    isPrescriptionRequired: true,
    isColdChain: false,
    isNarcotic: false,
    primaryUnitName: "Box (10x10)",
    status: "ACTIVE" as const,
  },
  {
    id: "med-6",
    brandName: "Insulin Mixtard 30 HM",
    genericName: "Human Insulin 30/70",
    strength: "100 IU/ml 10ml",
    dosageForm: "INJECTION" as const,
    categoryId: "cat-3",
    categoryName: "Cardiovascular & Antihypertensives",
    supplierId: "sup-3",
    supplierName: "Incepta Pharmaceuticals Ltd.",
    unitTradePrice: 396.00,
    unitMrp: 450.00,
    wholesaleBasePrice: 375.00,
    vatPercent: 0,
    storageCondition: "COLD_CHAIN_2_TO_8_C" as const,
    reorderAlertLevel: 30,
    totalStockOnHand: 45,
    isPrescriptionRequired: true,
    isColdChain: true,
    isNarcotic: false,
    primaryUnitName: "Vial",
    status: "ACTIVE" as const,
  },
];

export const MOCK_BATCHES = [
  {
    id: "batch-1",
    medicineId: "med-1",
    medicineName: "Napa Extra",
    genericName: "Paracetamol + Caffeine",
    batchNumber: "BX-NP-2401",
    manufacturingDate: "2024-01-10",
    expiryDate: "2026-12-31",
    quantityOnHand: 800,
    initialQuantity: 1000,
    unitCostPrice: 1.85,
    unitTradePrice: 2.20,
    unitMrp: 2.50,
    warehouseId: "wh-1",
    warehouseName: "Central Hub Tejgaon",
    rackName: "B-03",
    status: "ACTIVE" as const,
    isQuarantined: false,
  },
  {
    id: "batch-2",
    medicineId: "med-1",
    medicineName: "Napa Extra",
    genericName: "Paracetamol + Caffeine",
    batchNumber: "BX-NP-2405",
    manufacturingDate: "2024-05-15",
    expiryDate: "2027-04-30",
    quantityOnHand: 700,
    initialQuantity: 700,
    unitCostPrice: 1.88,
    unitTradePrice: 2.20,
    unitMrp: 2.50,
    warehouseId: "wh-1",
    warehouseName: "Central Hub Tejgaon",
    rackName: "B-03",
    status: "ACTIVE" as const,
    isQuarantined: false,
  },
  {
    id: "batch-3",
    medicineId: "med-3",
    medicineName: "Seclo 20",
    genericName: "Omeprazole",
    batchNumber: "SQ-SC-2309",
    manufacturingDate: "2023-09-01",
    expiryDate: "2026-09-30",
    quantityOnHand: 240,
    initialQuantity: 500,
    unitCostPrice: 3.65,
    unitTradePrice: 4.40,
    unitMrp: 5.00,
    warehouseId: "wh-1",
    warehouseName: "Central Hub Tejgaon",
    rackName: "A-01",
    status: "NEAR_EXPIRY" as const,
    isQuarantined: false,
  },
  {
    id: "batch-4",
    medicineId: "med-3",
    medicineName: "Seclo 20",
    genericName: "Omeprazole",
    batchNumber: "SQ-SC-2402",
    manufacturingDate: "2024-02-10",
    expiryDate: "2027-01-31",
    quantityOnHand: 600,
    initialQuantity: 600,
    unitCostPrice: 3.70,
    unitTradePrice: 4.40,
    unitMrp: 5.00,
    warehouseId: "wh-1",
    warehouseName: "Central Hub Tejgaon",
    rackName: "A-01",
    status: "ACTIVE" as const,
    isQuarantined: false,
  },
  {
    id: "batch-5",
    medicineId: "med-4",
    medicineName: "Ciprocin 500",
    genericName: "Ciprofloxacin",
    batchNumber: "SQ-CP-2401",
    manufacturingDate: "2024-01-20",
    expiryDate: "2026-11-30",
    quantityOnHand: 450,
    initialQuantity: 500,
    unitCostPrice: 10.90,
    unitTradePrice: 13.20,
    unitMrp: 15.00,
    warehouseId: "wh-1",
    warehouseName: "Central Hub Tejgaon",
    rackName: "A-01",
    status: "ACTIVE" as const,
    isQuarantined: false,
  },
  {
    id: "batch-6",
    medicineId: "med-6",
    medicineName: "Insulin Mixtard 30 HM",
    genericName: "Human Insulin 30/70",
    batchNumber: "INC-INS-2403",
    manufacturingDate: "2024-03-01",
    expiryDate: "2026-10-15",
    quantityOnHand: 45,
    initialQuantity: 60,
    unitCostPrice: 335.00,
    unitTradePrice: 396.00,
    unitMrp: 450.00,
    warehouseId: "wh-1",
    warehouseName: "Central Hub Tejgaon",
    rackName: "CR-01",
    status: "ACTIVE" as const,
    isQuarantined: false,
  },
];

export const MOCK_CUSTOMERS = [
  {
    id: "cust-1",
    tradeName: "Popular Model Pharmacy",
    proprietorName: "Dr. Mainul Islam",
    customerType: "RETAIL_PHARMACY" as const,
    drugLicenseNo: "DL-DH-84910",
    drugLicenseExpiry: "2027-06-30",
    tradeLicenseNo: "TL-POP-0912",
    taxIdTin: "4920192840",
    phone: "+880 1711 223344",
    email: "popular.model@pharmacy.com",
    deliveryAddress: "Shop 12, Mirpur 10 Circle",
    city: "Dhaka",
    assignedRoute: "Route 1: Mirpur - Pallabi",
    creditLimit: 300000,
    maxDueDays: 30,
    currentDue: 68500,
    oldestOverdueDays: 14,
    defaultDiscountPercent: 2.0,
    status: "ACTIVE" as const,
    totalSales: 450000,
  },
  {
    id: "cust-2",
    tradeName: "Labaid Hospital Dispensary",
    proprietorName: "Labaid Group Pharmacy Services",
    customerType: "HOSPITAL_DISPENSARY" as const,
    drugLicenseNo: "DL-DH-19283",
    drugLicenseExpiry: "2028-12-31",
    tradeLicenseNo: "TL-LAB-7712",
    taxIdTin: "9283748291",
    phone: "+880 1819 887766",
    email: "procurement.pharmacy@labaidgroup.com",
    deliveryAddress: "House 6, Road 4, Dhanmondi",
    city: "Dhaka",
    assignedRoute: "Route 2: Dhanmondi - Mohammadpur",
    creditLimit: 1500000,
    maxDueDays: 45,
    currentDue: 320000,
    oldestOverdueDays: 22,
    defaultDiscountPercent: 4.0,
    status: "ACTIVE" as const,
    totalSales: 2150000,
  },
  {
    id: "cust-3",
    tradeName: "Evergreen Drug Corner",
    proprietorName: "Kamrul Hasan",
    customerType: "RETAIL_PHARMACY" as const,
    drugLicenseNo: "DL-DH-44912",
    drugLicenseExpiry: "2026-09-15",
    tradeLicenseNo: "TL-EVR-3321",
    taxIdTin: "3829104821",
    phone: "+880 1912 334455",
    email: "evergreen.pharmacy@gmail.com",
    deliveryAddress: "Plot 8, Block C, Uttara Sector 3",
    city: "Dhaka",
    assignedRoute: "Route 3: Uttara - Tongi",
    creditLimit: 150000,
    maxDueDays: 30,
    currentDue: 142000,
    oldestOverdueDays: 38,
    defaultDiscountPercent: 0,
    status: "BLOCKED_OVERDUE" as const,
    totalSales: 310000,
  },
  {
    id: "cust-4",
    tradeName: "MediCare Clinic & Diagnostics",
    proprietorName: "Dr. Sabrina Chowdhury",
    customerType: "CLINIC_INSTITUTION" as const,
    drugLicenseNo: "DL-DH-55210",
    drugLicenseExpiry: "2027-11-20",
    tradeLicenseNo: "TL-MED-9921",
    taxIdTin: "5829104829",
    phone: "+880 1611 998877",
    email: "info@medicareclinic.com",
    deliveryAddress: "32 Green Road",
    city: "Dhaka",
    assignedRoute: "Route 2: Dhanmondi - Mohammadpur",
    creditLimit: 250000,
    maxDueDays: 30,
    currentDue: 18500,
    oldestOverdueDays: 5,
    defaultDiscountPercent: 2.5,
    status: "ACTIVE" as const,
    totalSales: 180000,
  },
];

export const MOCK_DISTRIBUTORS = [
  {
    id: "dist-1",
    name: "Tariqul Islam (MR)",
    phone: "+880 1718 112233",
    email: "tariqul.mr@pharmadist.com",
    assignedTerritory: "Dhaka North - Mirpur / Pallabi",
    dailyRouteBeat: "Route 1: Mirpur 1, 2, 10, 14 & Pallabi",
    monthlySalesTarget: 600000,
    currentMonthSales: 485000,
    recoveryAmount: 420000,
    commissionRatePercent: 2.5,
    earnedCommission: 12125,
    status: "ACTIVE" as const,
  },
  {
    id: "dist-2",
    name: "Mahfuzur Rahman (MR)",
    phone: "+880 1817 445566",
    email: "mahfuz.mr@pharmadist.com",
    assignedTerritory: "Dhaka Central - Dhanmondi / Green Rd",
    dailyRouteBeat: "Route 2: Dhanmondi, Science Lab, Green Road",
    monthlySalesTarget: 1000000,
    currentMonthSales: 890000,
    recoveryAmount: 760000,
    commissionRatePercent: 2.5,
    earnedCommission: 22250,
    status: "ACTIVE" as const,
  },
  {
    id: "dist-3",
    name: "Anisur Rahman (MR)",
    phone: "+880 1916 778899",
    email: "anis.mr@pharmadist.com",
    assignedTerritory: "Dhaka North - Uttara / Airport",
    dailyRouteBeat: "Route 3: Uttara Sectors 1-14 & Tongi Bazar",
    monthlySalesTarget: 500000,
    currentMonthSales: 310000,
    recoveryAmount: 260000,
    commissionRatePercent: 2.0,
    earnedCommission: 6200,
    status: "ACTIVE" as const,
  },
];

export const MOCK_INVOICES = [
  {
    id: "inv-1001",
    invoiceNumber: "INV-2026-00101",
    saleOrderId: "so-1001",
    challanNumber: "CH-2026-00084",
    customerId: "cust-1",
    customerName: "Popular Model Pharmacy",
    salesmanId: "dist-1",
    salesmanName: "Tariqul Islam (MR)",
    issueDate: "2026-08-15",
    dueDate: "2026-09-14",
    subtotal: 18400,
    discountAmount: 368,
    taxAmount: 0,
    grandTotal: 18032,
    cogsTotal: 15150,
    grossProfit: 2882,
    paidAmount: 18032,
    dueAmount: 0,
    status: "PAID" as const,
    deliveryStatus: "DELIVERED" as const,
    items: [
      {
        medicineName: "Napa Extra",
        genericName: "Paracetamol + Caffeine",
        dosageForm: "TABLET",
        batchNumber: "BX-NP-2401",
        expiryDate: "2026-12-31",
        quantity: 200,
        bonusQuantity: 10,
        unitPrice: 2.20,
        tradePrice: 2.20,
        mrp: 2.50,
        totalAmount: 440,
      },
    ],
  },
  {
    id: "inv-1002",
    invoiceNumber: "INV-2026-00102",
    saleOrderId: "so-1002",
    challanNumber: "CH-2026-00085",
    customerId: "cust-2",
    customerName: "Labaid Hospital Dispensary",
    salesmanId: "dist-2",
    salesmanName: "Mahfuzur Rahman (MR)",
    issueDate: "2026-08-18",
    dueDate: "2026-10-02",
    subtotal: 79200,
    discountAmount: 3168,
    taxAmount: 0,
    grandTotal: 76032,
    cogsTotal: 67000,
    grossProfit: 9032,
    paidAmount: 20000,
    dueAmount: 56032,
    status: "ISSUED" as const,
    deliveryStatus: "DELIVERED" as const,
    items: [
      {
        medicineName: "Insulin Mixtard 30 HM",
        genericName: "Human Insulin 30/70",
        dosageForm: "INJECTION",
        batchNumber: "INC-INS-2403",
        expiryDate: "2026-10-15",
        quantity: 200,
        bonusQuantity: 10,
        unitPrice: 396.00,
        tradePrice: 396.00,
        mrp: 450.00,
        totalAmount: 79200,
      },
    ],
  },
  {
    id: "inv-1003",
    invoiceNumber: "INV-2026-00103",
    saleOrderId: "so-1003",
    challanNumber: "CH-2026-00086",
    customerId: "cust-4",
    customerName: "MediCare Clinic & Diagnostics",
    salesmanId: "dist-2",
    salesmanName: "Mahfuzur Rahman (MR)",
    issueDate: "2026-08-21",
    dueDate: "2026-09-20",
    subtotal: 18500,
    discountAmount: 0,
    taxAmount: 0,
    grandTotal: 18500,
    cogsTotal: 15400,
    grossProfit: 3100,
    paidAmount: 0,
    dueAmount: 18500,
    status: "ISSUED" as const,
    deliveryStatus: "DISPATCHED" as const,
    items: [
      {
        medicineName: "Napa Extra",
        genericName: "Paracetamol + Caffeine",
        dosageForm: "TABLET",
        batchNumber: "BX-NP-2401",
        expiryDate: "2026-12-31",
        quantity: 500,
        bonusQuantity: 25,
        unitPrice: 2.20,
        tradePrice: 2.20,
        mrp: 2.50,
        totalAmount: 1100,
      },
    ],
  },
];

export const MOCK_PAYMENTS = [
  {
    id: "pay-01",
    receiptNo: "MR-2026-00381",
    customerId: "cust-1",
    customerName: "Popular Model Pharmacy",
    amount: 18032,
    paymentMethod: "CASH",
    paymentDate: "2026-08-16",
    status: "CONFIRMED",
    distributorName: "Tariqul Islam (MR)",
    chequeNumber: "",
    bankName: "",
    chequeStatus: "NOT_APPLICABLE",
  },
  {
    id: "pay-02",
    receiptNo: "MR-2026-00382",
    customerId: "cust-2",
    customerName: "Labaid Hospital Dispensary",
    amount: 20000,
    paymentMethod: "CHEQUE",
    paymentDate: "2026-08-19",
    chequeNumber: "CQ-8829104",
    bankName: "Dutch-Bangla Bank PLC",
    chequeStatus: "CLEARED",
    status: "CONFIRMED",
    distributorName: "Mahfuzur Rahman (MR)",
  },
  {
    id: "pay-03",
    receiptNo: "MR-2026-00383",
    customerId: "cust-3",
    customerName: "Evergreen Drug Corner",
    amount: 30000,
    paymentMethod: "CHEQUE",
    paymentDate: "2026-08-20",
    chequeNumber: "CQ-1928401",
    bankName: "Islami Bank Bangladesh",
    chequeStatus: "HOLDING",
    status: "CONFIRMED",
    distributorName: "Anisur Rahman (MR)",
  },
];

export const MOCK_EXPENSES = [
  {
    id: "exp-01",
    voucherNo: "EXP-2026-0091",
    categoryName: "Logistics & Van Fuel",
    amount: 14500,
    expenseDate: "2026-08-17",
    payeeName: "Meghna Fuel Station Tejgaon",
    paymentMethod: "CASH",
    description: "Diesel fuel for delivery vans (Dhaka Central & North routes)",
    status: "APPROVED",
  },
  {
    id: "exp-02",
    voucherNo: "EXP-2026-0092",
    categoryName: "Cold Chain Electricity & Generator",
    amount: 28000,
    expenseDate: "2026-08-19",
    payeeName: "DPDC Electricity Authority",
    paymentMethod: "BANK_TRANSFER",
    description: "Tejgaon central cold-room 24/7 climate control power bill",
    status: "APPROVED",
  },
  {
    id: "exp-03",
    voucherNo: "EXP-2026-0093",
    categoryName: "Warehouse Packaging Materials",
    amount: 6200,
    expenseDate: "2026-08-21",
    payeeName: "Dhaka Corrugated Box Supply",
    paymentMethod: "CASH",
    description: "Cartons, bubble wrap, and tamper-proof packing tape",
    status: "APPROVED",
  },
];

export const MOCK_AUDIT_LOGS = [
  {
    id: "log-1",
    action: "INVOICE_GENERATED",
    entityName: "Invoice",
    entityId: "inv-1003",
    userName: "Kamal Hossain (Sales Mgr)",
    timestamp: "2026-08-21T11:45:00Z",
    details: "Generated Wholesale Tax Invoice INV-2026-00103 with FEFO batch allocation BX-NP-2401.",
  },
  {
    id: "log-2",
    action: "BATCH_INTAKE_GRN",
    entityName: "PurchaseItem",
    entityId: "grn-2026-0044",
    userName: "Tareq Mahmud (Warehouse Mgr)",
    timestamp: "2026-08-20T16:20:00Z",
    details: "Received 500 units of Napa Extra (Batch BX-NP-2405, Exp 2027-04-30) from Beximco Pharma.",
  },
  {
    id: "log-3",
    action: "CUSTOMER_CREDIT_HOLD",
    entityName: "Customer",
    entityId: "cust-3",
    userName: "System Automated Rule",
    timestamp: "2026-08-20T08:00:00Z",
    details: "Evergreen Drug Corner status updated to BLOCKED_OVERDUE (38 days overdue, exceeding 30-day limit).",
  },
  {
    id: "log-4",
    action: "PAYMENT_RECORDED",
    entityName: "CustomerPayment",
    entityId: "pay-01",
    userName: "Shahidul Alam (Accounts)",
    timestamp: "2026-08-16T14:10:00Z",
    details: "Received ৳18,032 cash payment for Popular Model Pharmacy against INV-2026-00101.",
  },
];
